Repository splunk-soar-connectors/cscdomainmanager, pull requests merged in 2023-02, with the labels that each got.

#1 cscdomainmanager: New app - Initial release
  .pre-commit-config.yaml
  LICENSE
  __init__.py
  cscdomainmanager.json
  cscdomainmanager_connector.py
  cscdomainmanager_consts.py
  logo_cscdomainmanager.svg
  logo_cscdomainmanager_dark.svg
  readme.html
  release_notes/unreleased.md
  requirements.txt
  tox.ini
  wheels/py3/beautifulsoup4-4.9.1-py3-none-any.whl
  wheels/py3/certifi-2022.12.7-py3-none-any.whl
  wheels/py3/soupsieve-2.3.2.post1-py3-none-any.whl
  wheels/shared/chardet-3.0.4-py2.py3-none-any.whl
  wheels/shared/idna-2.10-py2.py3-none-any.whl
  wheels/shared/requests-2.25.0-py2.py3-none-any.whl
  wheels/shared/urllib3-1.26.14-py2.py3-none-any.whl
Labels: external-contributor, splunk-supported, PAPP-29258

#2 PAPP-29258: Updating release notes
  release_notes/unreleased.md
Labels: developer-supported

#4 PAPP-29258: Updating product name
  cscdomainmanager.json
Labels: developer-supported

#5 PAPP-29512: Add "get order status" action
  LICENSE
  cscdomainmanager.json
  cscdomainmanager_connector.py
  release_notes/unreleased.md
  wheels/py3/soupsieve-2.4-py3-none-any.whl
Labels: external-contributor, developer-supported, PAPP-29512
